language: python
python:
    - "2.7"
install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install https://github.com/VioletGiraffe/cpp-template-utils
    - platformio lib -g install "Adafruit GFX Library"
    - platformio lib -g install "FastLED"
script:
    - platformio ci --lib="." --board=due ./examples/TwoScreens/
    - platformio ci --lib="." --board=due ./examples/RGBLedMatrix/